// This file is auto-generated by @hey-api/openapi-ts

export const $AccessLevel = {
    type: 'string',
    enum: ['public', 'private'],
    title: 'AccessLevel'
} as const;

export const $AlbumCreate = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        event_id: {
            type: 'string',
            format: 'uuid',
            title: 'Event Id'
        }
    },
    type: 'object',
    required: ['name', 'event_id'],
    title: 'AlbumCreate'
} as const;

export const $AlbumPublic = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        event_id: {
            type: 'string',
            format: 'uuid',
            title: 'Event Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'event_id'],
    title: 'AlbumPublic'
} as const;

export const $AlbumUpdate = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'AlbumUpdate'
} as const;

export const $AlbumsPublic = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AlbumPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AlbumsPublic'
} as const;

export const $Body_login_login_access_token = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const $Comment = {
    properties: {
        text: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Text'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        media_id: {
            type: 'string',
            format: 'uuid',
            title: 'Media Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['text', 'user_id', 'media_id'],
    title: 'Comment'
} as const;

export const $CommentCreate = {
    properties: {
        text: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Text'
        },
        media_id: {
            type: 'string',
            format: 'uuid',
            title: 'Media Id'
        }
    },
    type: 'object',
    required: ['text', 'media_id'],
    title: 'CommentCreate'
} as const;

export const $EventCreate = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        event_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Event Date'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'EventCreate'
} as const;

export const $EventPublic = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        event_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Event Date'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        creator_id: {
            type: 'string',
            format: 'uuid',
            title: 'Creator Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'creator_id'],
    title: 'EventPublic'
} as const;

export const $EventUpdate = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        event_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Event Date'
        }
    },
    type: 'object',
    title: 'EventUpdate'
} as const;

export const $EventsPublic = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/EventPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'EventsPublic'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $MediaCreate = {
    properties: {
        filename: {
            type: 'string',
            maxLength: 500,
            title: 'Filename'
        },
        media_type: {
            '$ref': '#/components/schemas/MediaType'
        },
        access_level: {
            '$ref': '#/components/schemas/AccessLevel',
            default: 'private'
        },
        file_size: {
            type: 'integer',
            title: 'File Size',
            default: 0
        },
        file_path: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Path'
        },
        event_id: {
            type: 'string',
            format: 'uuid',
            title: 'Event Id'
        },
        album_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Album Id'
        }
    },
    type: 'object',
    required: ['filename', 'media_type', 'event_id'],
    title: 'MediaCreate'
} as const;

export const $MediaPublic = {
    properties: {
        filename: {
            type: 'string',
            maxLength: 500,
            title: 'Filename'
        },
        media_type: {
            '$ref': '#/components/schemas/MediaType'
        },
        access_level: {
            '$ref': '#/components/schemas/AccessLevel',
            default: 'private'
        },
        file_size: {
            type: 'integer',
            title: 'File Size',
            default: 0
        },
        file_path: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Path'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        uploader_id: {
            type: 'string',
            format: 'uuid',
            title: 'Uploader Id'
        },
        event_id: {
            type: 'string',
            format: 'uuid',
            title: 'Event Id'
        },
        album_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Album Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['filename', 'media_type', 'id', 'uploader_id', 'event_id'],
    title: 'MediaPublic'
} as const;

export const $MediaTag = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        tag_name: {
            type: 'string',
            maxLength: 255,
            title: 'Tag Name'
        },
        confidence: {
            type: 'number',
            title: 'Confidence',
            default: 0
        },
        media_id: {
            type: 'string',
            format: 'uuid',
            title: 'Media Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['tag_name', 'media_id'],
    title: 'MediaTag'
} as const;

export const $MediaTagCreate = {
    properties: {
        tag_name: {
            type: 'string',
            title: 'Tag Name'
        },
        confidence: {
            type: 'number',
            title: 'Confidence',
            default: 0
        }
    },
    type: 'object',
    required: ['tag_name'],
    title: 'MediaTagCreate'
} as const;

export const $MediaType = {
    type: 'string',
    enum: ['photo', 'video'],
    title: 'MediaType'
} as const;

export const $MediaUpdate = {
    properties: {
        access_level: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/AccessLevel'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'MediaUpdate'
} as const;

export const $MediasPublic = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MediaPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MediasPublic'
} as const;

export const $Message = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const $NewPassword = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const $NotificationPublic = {
    properties: {
        type: {
            '$ref': '#/components/schemas/NotificationType'
        },
        message: {
            type: 'string',
            maxLength: 500,
            title: 'Message'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        is_read: {
            type: 'boolean',
            title: 'Is Read'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['type', 'message', 'id', 'user_id', 'is_read'],
    title: 'NotificationPublic'
} as const;

export const $NotificationType = {
    type: 'string',
    enum: ['like', 'comment', 'tag'],
    title: 'NotificationType'
} as const;

export const $PrivateUserCreate = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const $Token = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const $UpdatePassword = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const $UserCreate = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'viewer'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const $UserPublic = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'viewer'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const $UserRegister = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const $UserRole = {
    type: 'string',
    enum: ['admin', 'photographer', 'club_member', 'viewer'],
    title: 'UserRole'
} as const;

export const $UserTagCreate = {
    properties: {
        tagged_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Tagged User Id'
        }
    },
    type: 'object',
    required: ['tagged_user_id'],
    title: 'UserTagCreate'
} as const;

export const $UserUpdate = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UserRole'
                },
                {
                    type: 'null'
                }
            ]
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const $UserUpdateMe = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const $UsersPublic = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;