// This file is auto-generated by @hey-api/openapi-ts

export type AccessLevel = 'public' | 'private';

export type AlbumCreate = {
    name: string;
    description?: string | null;
    event_id: string;
};

export type AlbumPublic = {
    name: string;
    description?: string | null;
    id: string;
    event_id: string;
    created_at?: string | null;
};

export type AlbumUpdate = {
    name?: string | null;
    description?: string | null;
};

export type AlbumsPublic = {
    data: Array<AlbumPublic>;
    count: number;
};

export type Body_login_login_access_token = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type Comment = {
    text: string;
    id?: string;
    user_id: string;
    media_id: string;
    created_at?: string | null;
};

export type CommentCreate = {
    text: string;
    media_id: string;
};

export type EventCreate = {
    name: string;
    description?: string | null;
    category?: string | null;
    event_date?: string | null;
};

export type EventPublic = {
    name: string;
    description?: string | null;
    category?: string | null;
    event_date?: string | null;
    id: string;
    creator_id: string;
    created_at?: string | null;
};

export type EventUpdate = {
    name?: string | null;
    description?: string | null;
    category?: string | null;
    event_date?: string | null;
};

export type EventsPublic = {
    data: Array<EventPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MediaCreate = {
    filename: string;
    media_type: MediaType;
    access_level?: AccessLevel;
    file_size?: number;
    file_path?: string | null;
    event_id: string;
    album_id?: string | null;
};

export type MediaPublic = {
    filename: string;
    media_type: MediaType;
    access_level?: AccessLevel;
    file_size?: number;
    file_path?: string | null;
    id: string;
    uploader_id: string;
    event_id: string;
    album_id?: string | null;
    created_at?: string | null;
};

export type MediaTag = {
    id?: string;
    tag_name: string;
    confidence?: number;
    media_id: string;
    created_at?: string | null;
};

export type MediaTagCreate = {
    tag_name: string;
    confidence?: number;
};

export type MediaType = 'photo' | 'video';

export type MediaUpdate = {
    access_level?: AccessLevel | null;
};

export type MediasPublic = {
    data: Array<MediaPublic>;
    count: number;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NotificationPublic = {
    type: NotificationType;
    message: string;
    id: string;
    user_id: string;
    is_read: boolean;
    created_at?: string | null;
};

export type NotificationType = 'like' | 'comment' | 'tag';

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    full_name?: string | null;
    role?: UserRole;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    full_name?: string | null;
    role?: UserRole;
    id: string;
    created_at?: string | null;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: string | null;
};

export type UserRole = 'ADMIN' | 'PHOTOGRAPHER' | 'CLUB_MEMBER' | 'VIEWER';

export type UserTagCreate = {
    tagged_user_id: string;
};

export type UserUpdate = {
    email?: string | null;
    is_active?: boolean;
    full_name?: string | null;
    role?: UserRole | null;
    password?: string | null;
};

export type UserUpdateMe = {
    full_name?: string | null;
    email?: string | null;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = Token;

export type LoginTestTokenResponse = UserPublic;

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = Message;

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = Message;

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = string;

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = UsersPublic;

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = UserPublic;

export type UsersReadUserMeResponse = UserPublic;

export type UsersDeleteUserMeResponse = Message;

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = UserPublic;

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = Message;

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = UserPublic;

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = UserPublic;

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = UserPublic;

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = Message;

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = Message;

export type UtilsHealthCheckResponse = boolean;

export type EventsReadEventsData = {
    limit?: number;
    skip?: number;
};

export type EventsReadEventsResponse = EventsPublic;

export type EventsCreateEventData = {
    requestBody: EventCreate;
};

export type EventsCreateEventResponse = EventPublic;

export type EventsReadEventData = {
    eventId: string;
};

export type EventsReadEventResponse = EventPublic;

export type EventsUpdateEventData = {
    eventId: string;
    requestBody: EventUpdate;
};

export type EventsUpdateEventResponse = EventPublic;

export type EventsDeleteEventData = {
    eventId: string;
};

export type EventsDeleteEventResponse = Message;

export type AlbumsReadAlbumsByEventData = {
    eventId: string;
};

export type AlbumsReadAlbumsByEventResponse = AlbumsPublic;

export type AlbumsReadAlbumData = {
    albumId: string;
};

export type AlbumsReadAlbumResponse = AlbumPublic;

export type AlbumsUpdateAlbumData = {
    albumId: string;
    requestBody: AlbumUpdate;
};

export type AlbumsUpdateAlbumResponse = AlbumPublic;

export type AlbumsDeleteAlbumData = {
    albumId: string;
};

export type AlbumsDeleteAlbumResponse = Message;

export type AlbumsCreateAlbumData = {
    requestBody: AlbumCreate;
};

export type AlbumsCreateAlbumResponse = AlbumPublic;

export type MediaReadMediaByEventData = {
    eventId: string;
    limit?: number;
    skip?: number;
};

export type MediaReadMediaByEventResponse = MediasPublic;

export type MediaReadMediaByAlbumData = {
    albumId: string;
};

export type MediaReadMediaByAlbumResponse = MediasPublic;

export type MediaReadMediaData = {
    mediaId: string;
};

export type MediaReadMediaResponse = MediaPublic;

export type MediaUpdateMediaData = {
    mediaId: string;
    requestBody: MediaUpdate;
};

export type MediaUpdateMediaResponse = MediaPublic;

export type MediaDeleteMediaData = {
    mediaId: string;
};

export type MediaDeleteMediaResponse = Message;

export type MediaCreateMediaData = {
    requestBody: MediaCreate;
};

export type MediaCreateMediaResponse = MediaPublic;

export type MediaLikeMediaData = {
    mediaId: string;
};

export type MediaLikeMediaResponse = Message;

export type MediaUnlikeMediaData = {
    mediaId: string;
};

export type MediaUnlikeMediaResponse = Message;

export type MediaReadCommentsData = {
    mediaId: string;
};

export type MediaReadCommentsResponse = Array<Comment>;

export type MediaCreateCommentData = {
    mediaId: string;
    requestBody: CommentCreate;
};

export type MediaCreateCommentResponse = Comment;

export type MediaAddFavoriteData = {
    mediaId: string;
};

export type MediaAddFavoriteResponse = MediaPublic;

export type MediaRemoveFavoriteData = {
    mediaId: string;
};

export type MediaRemoveFavoriteResponse = Message;

export type MediaReadMediaTagsData = {
    mediaId: string;
};

export type MediaReadMediaTagsResponse = Array<MediaTag>;

export type MediaCreateMediaTagData = {
    mediaId: string;
    requestBody: MediaTagCreate;
};

export type MediaCreateMediaTagResponse = MediaTag;

export type MediaCreateUserTagData = {
    mediaId: string;
    requestBody: UserTagCreate;
};

export type MediaCreateUserTagResponse = Message;

export type NotificationsReadNotificationsData = {
    limit?: number;
    skip?: number;
};

export type NotificationsReadNotificationsResponse = Array<NotificationPublic>;

export type NotificationsMarkNotificationReadData = {
    notificationId: string;
};

export type NotificationsMarkNotificationReadResponse = NotificationPublic;

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = UserPublic;

export type $OpenApiTs = {
    '/api/v1/login/access-token': {
        post: {
            req: {
                formData: Body_login_login_access_token;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Token;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/login/test-token': {
        post: {
            res: {
                /**
                 * Successful Response
                 */
                200: UserPublic;
            };
        };
    };
    '/api/v1/password-recovery/{email}': {
        post: {
            req: {
                email: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Message;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/reset-password/': {
        post: {
            req: {
                requestBody: NewPassword;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Message;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/password-recovery-html-content/{email}': {
        post: {
            req: {
                email: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: string;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/users/': {
        get: {
            req: {
                limit?: number;
                skip?: number;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: UsersPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: {
                requestBody: UserCreate;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: UserPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/users/me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: UserPublic;
            };
        };
        delete: {
            res: {
                /**
                 * Successful Response
                 */
                200: Message;
            };
        };
        patch: {
            req: {
                requestBody: UserUpdateMe;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: UserPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/users/me/password': {
        patch: {
            req: {
                requestBody: UpdatePassword;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Message;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/users/signup': {
        post: {
            req: {
                requestBody: UserRegister;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: UserPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/users/{user_id}': {
        get: {
            req: {
                userId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: UserPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: {
                requestBody: UserUpdate;
                userId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: UserPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: {
                userId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Message;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/utils/test-email/': {
        post: {
            req: {
                emailTo: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                201: Message;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/utils/health-check/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: boolean;
            };
        };
    };
    '/api/v1/events/': {
        get: {
            req: {
                limit?: number;
                skip?: number;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: EventsPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: {
                requestBody: EventCreate;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: EventPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/events/{event_id}': {
        get: {
            req: {
                eventId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: EventPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: {
                eventId: string;
                requestBody: EventUpdate;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: EventPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: {
                eventId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Message;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/albums/event/{event_id}': {
        get: {
            req: {
                eventId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: AlbumsPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/albums/{album_id}': {
        get: {
            req: {
                albumId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: AlbumPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: {
                albumId: string;
                requestBody: AlbumUpdate;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: AlbumPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: {
                albumId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Message;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/albums/': {
        post: {
            req: {
                requestBody: AlbumCreate;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: AlbumPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/media/event/{event_id}': {
        get: {
            req: {
                eventId: string;
                limit?: number;
                skip?: number;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: MediasPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/media/album/{album_id}': {
        get: {
            req: {
                albumId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: MediasPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/media/{media_id}': {
        get: {
            req: {
                mediaId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: MediaPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: {
                mediaId: string;
                requestBody: MediaUpdate;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: MediaPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: {
                mediaId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Message;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/media/': {
        post: {
            req: {
                requestBody: MediaCreate;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: MediaPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/media/{media_id}/like': {
        post: {
            req: {
                mediaId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Message;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: {
                mediaId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Message;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/media/{media_id}/comments': {
        get: {
            req: {
                mediaId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Array<Comment>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: {
                mediaId: string;
                requestBody: CommentCreate;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Comment;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/media/{media_id}/favorites': {
        post: {
            req: {
                mediaId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: MediaPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: {
                mediaId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Message;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/media/{media_id}/tags': {
        get: {
            req: {
                mediaId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Array<MediaTag>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: {
                mediaId: string;
                requestBody: MediaTagCreate;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: MediaTag;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/media/{media_id}/user-tags': {
        post: {
            req: {
                mediaId: string;
                requestBody: UserTagCreate;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Message;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/notifications/': {
        get: {
            req: {
                limit?: number;
                skip?: number;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: Array<NotificationPublic>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/notifications/{notification_id}/read': {
        patch: {
            req: {
                notificationId: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: NotificationPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/private/users/': {
        post: {
            req: {
                requestBody: PrivateUserCreate;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: UserPublic;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};
